name: Build the LaTeX

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/checkout@v4
      - name: Build the LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: spec.tex
          working_directory: docs
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: spec.pdf
          path: docs/spec.pdf
